apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: 
      cpu: 200m
    defaultRequest: 
      cpu: 100m
    max: 
      cpu: "1"
    min:
      cpu: 50m
    type: Container
